{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: confluent-replicator-credentials
  labels:
    app: confluent-replicator
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: SecretStore
  target:
    name: {{ .Values.replicator.credentialsSecretName }}
  data:
    - secretKey: src-api-key
      remoteRef:
        key: {{ .Values.replicator.source.ssmPath }}
        property: kafka_api_key
    - secretKey: src-api-secret
      remoteRef:
        key: {{ .Values.replicator.source.ssmPath }}
        property: kafka_api_secret
    - secretKey: dst-api-key
      remoteRef:
        key: {{ .Values.replicator.destination.ssmPath }}
        property: kafka_api_key
    - secretKey: dst-api-secret
      remoteRef:
        key: {{ .Values.replicator.destination.ssmPath }}
        property: kafka_api_secret
{{- end }}
